services:
    seraph_menu.manager:
        class: Seraph\Bundle\MenuBundle\Manager\MenuManager
        arguments: ['@form.factory', '%seraph_menu.admin.menu_depth'

    seraph_menu.twig.extension:
          class: Seraph\Bundle\MenuBundle\Twig\MenuExtension
          tags: ['twig.extension']