services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Seraph\Bundle\MenuBundle\:
        resource: '../../*'
        exclude: '../../{Controller,Entity,Form,Resources,Twig}'