services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    seraph_menu.manager:
        class: Seraph\Bundle\MenuBundle\Manager\MenuManger
         arguments: ['@form.factory', '%seraph_menu.manager.menu_depth%']

    Seraph\Bundle\MenuBundle\:
        resource: '../../*'
