services:
    seraph.menu.manager:
        class: Seraph\Bundle\MenuBundle\Manager\MenuManager
        arguments: ['@form.factory', '%seraph_menu.admin.menu_depth'

    seraph.menu.twig_extension:
          class: Seraph\Bundle\MenuBundle\Twig\MenuExtension
          tags:
              - { name: seraph_function, priority: 255}