services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Seraph\Bundle\MenuBundle\:
        resource: '../../*'
        exclude: '../../{Controller,Entity,Form,Resources,Twig}'

    Seraph\Bundle\MenuBundle\Controller\:
        resource : '../../Controller'
        tags: ['controller.service_arguments']