services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Seraph\Bundle\MenuBundle\:
        resource: '../../*'
              exclude: '../src/{Controller,Entity,Form,Resources,Twig}'
