services:
    Seraph\Bundle\MenuBundle\Twig\:
            resource: '../../Twig'
            tags: ['controller.service_arguments', 'twig.extension']
            arguments:
                        $registry: '@doctrine'
                        $twig: '@twig'